### ISSUE TITLE
NPM start

### ISSUE THREAD

**Issue by ramizkamel** [exiled-apes/candy-machine-mint#156]
Hi there, I followed everything on the code section and when i run NPM start, I get this error message in my web browser:
![Screenshot 2021-11-01 at 8 24 40 am](https://user-images.githubusercontent.com/90847835/139640927-6d95e399-dcc9-4f51-976b-6a76a71b7628.jpg)
Any help or suggestions to solve this problem would be appreciated!

**Comment by happyclan** [comment]
does your .env file have .env.example still?  rename it to .env  guessing you're on windows with file extensions hidden.

**Comment by conrad765** [comment]
> does your .env file have .env.example still? rename it to .env guessing you're on windows with file extensions hidden.

I have the same error currently and our .env file is configured properly :/

**Comment by NickTeez** [comment]
Yeah i have the same error too, every time I run yarn star and go to the local browser it comes up with this error. Using a mac and have removed the example from the .env file...

**Comment by conrad765** [comment]
Oh yeah the issue is you likely have you file named env.env if you go into file explorer and turn on view extensions just set the extension name as .env and have no text before it, that should fix it mate :)

**Comment by conrad765** [comment]
@ramizkamel @NickTeez see my previous message for a fix if you're still struggling guys

**Comment by NickTeez** [comment]
Nah sorry still not working getting the same error
<img width="1047" alt="Screen Shot 2021-11-25 at 8 43 59 PM" src="https://user-images.githubusercontent.com/95014405/143400267-214d39ff-4711-4f7d-921f-62e8cd9012e1.png">
or
